In [18]:
import pandas as pd  
import matplotlib.pylab as plt  
%matplotlib inline  
import numpy as np  
from scipy.stats import linregress  
import scipy.stats as stats  
from sklearn.tree import DecisionTreeClassifier  
from sklearn.metrics import confusion_matrix  
from matplotlib.colors import ListedColormap  
from sklearn.ensemble import RandomForestClassifier  
from sklearn.cluster import KMeans  
from sklearn.preprocessing import StandardScaler  
from sklearn.model_selection import train_test_split

In [19]:
# # Read CSV files from Wendy directories
calendar = pd.read_csv("D:\year3\FIT3163\Project\calendar.csv")
evaluation = pd.read_csv("D:\year3\FIT3163\Project\sales_train_evaluation.csv")
validation = pd.read_csv("D:\year3\FIT3163\Project\sales_train_validation.csv")
prices = pd.read_csv("D:\year3\FIT3163\Project\sell_prices.csv")
sample = pd.read_csv("D:\year3\FIT3163\Project\sample_submission.csv")

In [3]:
#Janice repo
calendar = pd.read_csv('D:\\YEAR 3\\Semester 2\\backup\\calendar.csv')
evaluation = pd.read_csv('D:\\YEAR 3\\Semester 2\\backup\\sales_train_evaluation.csv')
validation = pd.read_csv('D:\\YEAR 3\\Semester 2\\backup\\sales_train_validation.csv')
sample = pd.read_csv('D:\\YEAR 3\\Semester 2\\backup\\sample_submission.csv')
prices = pd.read_csv('D:\\YEAR 3\\Semester 2\\backup\\sell_prices.csv')

In [20]:
d_cols = [col for col in evaluation.columns if col.startswith('d_')]
d_cols

['d_1',
 'd_2',
 'd_3',
 'd_4',
 'd_5',
 'd_6',
 'd_7',
 'd_8',
 'd_9',
 'd_10',
 'd_11',
 'd_12',
 'd_13',
 'd_14',
 'd_15',
 'd_16',
 'd_17',
 'd_18',
 'd_19',
 'd_20',
 'd_21',
 'd_22',
 'd_23',
 'd_24',
 'd_25',
 'd_26',
 'd_27',
 'd_28',
 'd_29',
 'd_30',
 'd_31',
 'd_32',
 'd_33',
 'd_34',
 'd_35',
 'd_36',
 'd_37',
 'd_38',
 'd_39',
 'd_40',
 'd_41',
 'd_42',
 'd_43',
 'd_44',
 'd_45',
 'd_46',
 'd_47',
 'd_48',
 'd_49',
 'd_50',
 'd_51',
 'd_52',
 'd_53',
 'd_54',
 'd_55',
 'd_56',
 'd_57',
 'd_58',
 'd_59',
 'd_60',
 'd_61',
 'd_62',
 'd_63',
 'd_64',
 'd_65',
 'd_66',
 'd_67',
 'd_68',
 'd_69',
 'd_70',
 'd_71',
 'd_72',
 'd_73',
 'd_74',
 'd_75',
 'd_76',
 'd_77',
 'd_78',
 'd_79',
 'd_80',
 'd_81',
 'd_82',
 'd_83',
 'd_84',
 'd_85',
 'd_86',
 'd_87',
 'd_88',
 'd_89',
 'd_90',
 'd_91',
 'd_92',
 'd_93',
 'd_94',
 'd_95',
 'd_96',
 'd_97',
 'd_98',
 'd_99',
 'd_100',
 'd_101',
 'd_102',
 'd_103',
 'd_104',
 'd_105',
 'd_106',
 'd_107',
 'd_108',
 'd_109',
 'd_110',
 'd_111',
 'd_112',
 'd_113',
 'd_114',
 'd_115',
 'd_116',
 'd_117',
 'd_118',
 'd_119',
 'd_120',
 'd_121',
 'd_122',
 'd_123',
 'd_124',
 'd_125',
 'd_126',
 'd_127',
 'd_128',
 'd_129',
 'd_130',
 'd_131',
 'd_132',
 'd_133',
 'd_134',
 'd_135',
 'd_136',
 'd_137',
 'd_138',
 'd_139',
 'd_140',
 'd_141',
 'd_142',
 'd_143',
 'd_144',
 'd_145',
 'd_146',
 'd_147',
 'd_148',
 'd_149',
 'd_150',
 'd_151',
 'd_152',
 'd_153',
 'd_154',
 'd_155',
 'd_156',
 'd_157',
 'd_158',
 'd_159',
 'd_160',
 'd_161',
 'd_162',
 'd_163',
 'd_164',
 'd_165',
 'd_166',
 'd_167',
 'd_168',
 'd_169',
 'd_170',
 'd_171',
 'd_172',
 'd_173',
 'd_174',
 'd_175',
 'd_176',
 'd_177',
 'd_178',
 'd_179',
 'd_180',
 'd_181',
 'd_182',
 'd_183',
 'd_184',
 'd_185',
 'd_186',
 'd_187',
 'd_188',
 'd_189',
 'd_190',
 'd_191',
 'd_192',
 'd_193',
 'd_194',
 'd_195',
 'd_196',
 'd_197',
 'd_198',
 'd_199',
 'd_200',
 'd_201',
 'd_202',
 'd_203',
 'd_204',
 'd_205',
 'd_206',
 'd_207',
 'd_208',
 'd_209',
 'd_210',
 'd_211',
 'd_212',
 'd_213',
 'd_214',
 'd_215',
 'd_216',
 'd_217',
 'd_218',
 'd_219',
 'd_220',
 'd_221',
 'd_222',
 'd_223',
 'd_224',
 'd_225',
 'd_226',
 'd_227',
 'd_228',
 'd_229',
 'd_230',
 'd_231',
 'd_232',
 'd_233',
 'd_234',
 'd_235',
 'd_236',
 'd_237',
 'd_238',
 'd_239',
 'd_240',
 'd_241',
 'd_242',
 'd_243',
 'd_244',
 'd_245',
 'd_246',
 'd_247',
 'd_248',
 'd_249',
 'd_250',
 'd_251',
 'd_252',
 'd_253',
 'd_254',
 'd_255',
 'd_256',
 'd_257',
 'd_258',
 'd_259',
 'd_260',
 'd_261',
 'd_262',
 'd_263',
 'd_264',
 'd_265',
 'd_266',
 'd_267',
 'd_268',
 'd_269',
 'd_270',
 'd_271',
 'd_272',
 'd_273',
 'd_274',
 'd_275',
 'd_276',
 'd_277',
 'd_278',
 'd_279',
 'd_280',
 'd_281',
 'd_282',
 'd_283',
 'd_284',
 'd_285',
 'd_286',
 'd_287',
 'd_288',
 'd_289',
 'd_290',
 'd_291',
 'd_292',
 'd_293',
 'd_294',
 'd_295',
 'd_296',
 'd_297',
 'd_298',
 'd_299',
 'd_300',
 'd_301',
 'd_302',
 'd_303',
 'd_304',
 'd_305',
 'd_306',
 'd_307',
 'd_308',
 'd_309',
 'd_310',
 'd_311',
 'd_312',
 'd_313',
 'd_314',
 'd_315',
 'd_316',
 'd_317',
 'd_318',
 'd_319',
 'd_320',
 'd_321',
 'd_322',
 'd_323',
 'd_324',
 'd_325',
 'd_326',
 'd_327',
 'd_328',
 'd_329',
 'd_330',
 'd_331',
 'd_332',
 'd_333',
 'd_334',
 'd_335',
 'd_336',
 'd_337',
 'd_338',
 'd_339',
 'd_340',
 'd_341',
 'd_342',
 'd_343',
 'd_344',
 'd_345',
 'd_346',
 'd_347',
 'd_348',
 'd_349',
 'd_350',
 'd_351',
 'd_352',
 'd_353',
 'd_354',
 'd_355',
 'd_356',
 'd_357',
 'd_358',
 'd_359',
 'd_360',
 'd_361',
 'd_362',
 'd_363',
 'd_364',
 'd_365',
 'd_366',
 'd_367',
 'd_368',
 'd_369',
 'd_370',
 'd_371',
 'd_372',
 'd_373',
 'd_374',
 'd_375',
 'd_376',
 'd_377',
 'd_378',
 'd_379',
 'd_380',
 'd_381',
 'd_382',
 'd_383',
 'd_384',
 'd_385',
 'd_386',
 'd_387',
 'd_388',
 'd_389',
 'd_390',
 'd_391',
 'd_392',
 'd_393',
 'd_394',
 'd_395',
 'd_396',
 'd_397',
 'd_398',
 'd_399',
 'd_400',
 'd_401',
 'd_402',
 'd_403',
 'd_404',
 'd_405',
 'd_406',
 'd_407',
 'd_408',
 'd_409',
 'd_410',
 'd_411',
 'd_412',
 'd_413',
 'd_414',
 'd_415',
 'd_416',
 'd_417',
 'd_418',
 'd_419',
 'd_420',
 'd_421',
 'd_422',
 'd_423',
 'd_424',
 'd_425',
 'd_426',
 'd_427',
 'd_428',
 'd_429',
 'd_430',
 'd_431',
 'd_432',
 'd_433',
 'd_434',
 'd_435',
 'd_436',
 'd_437',
 'd_438',
 'd_439',
 'd_440',
 'd_441',
 'd_442',
 'd_443',
 'd_444',
 'd_445',
 'd_446',
 'd_447',
 'd_448',
 'd_449',
 'd_450',
 'd_451',
 'd_452',
 'd_453',
 'd_454',
 'd_455',
 'd_456',
 'd_457',
 'd_458',
 'd_459',
 'd_460',
 'd_461',
 'd_462',
 'd_463',
 'd_464',
 'd_465',
 'd_466',
 'd_467',
 'd_468',
 'd_469',
 'd_470',
 'd_471',
 'd_472',
 'd_473',
 'd_474',
 'd_475',
 'd_476',
 'd_477',
 'd_478',
 'd_479',
 'd_480',
 'd_481',
 'd_482',
 'd_483',
 'd_484',
 'd_485',
 'd_486',
 'd_487',
 'd_488',
 'd_489',
 'd_490',
 'd_491',
 'd_492',
 'd_493',
 'd_494',
 'd_495',
 'd_496',
 'd_497',
 'd_498',
 'd_499',
 'd_500',
 'd_501',
 'd_502',
 'd_503',
 'd_504',
 'd_505',
 'd_506',
 'd_507',
 'd_508',
 'd_509',
 'd_510',
 'd_511',
 'd_512',
 'd_513',
 'd_514',
 'd_515',
 'd_516',
 'd_517',
 'd_518',
 'd_519',
 'd_520',
 'd_521',
 'd_522',
 'd_523',
 'd_524',
 'd_525',
 'd_526',
 'd_527',
 'd_528',
 'd_529',
 'd_530',
 'd_531',
 'd_532',
 'd_533',
 'd_534',
 'd_535',
 'd_536',
 'd_537',
 'd_538',
 'd_539',
 'd_540',
 'd_541',
 'd_542',
 'd_543',
 'd_544',
 'd_545',
 'd_546',
 'd_547',
 'd_548',
 'd_549',
 'd_550',
 'd_551',
 'd_552',
 'd_553',
 'd_554',
 'd_555',
 'd_556',
 'd_557',
 'd_558',
 'd_559',
 'd_560',
 'd_561',
 'd_562',
 'd_563',
 'd_564',
 'd_565',
 'd_566',
 'd_567',
 'd_568',
 'd_569',
 'd_570',
 'd_571',
 'd_572',
 'd_573',
 'd_574',
 'd_575',
 'd_576',
 'd_577',
 'd_578',
 'd_579',
 'd_580',
 'd_581',
 'd_582',
 'd_583',
 'd_584',
 'd_585',
 'd_586',
 'd_587',
 'd_588',
 'd_589',
 'd_590',
 'd_591',
 'd_592',
 'd_593',
 'd_594',
 'd_595',
 'd_596',
 'd_597',
 'd_598',
 'd_599',
 'd_600',
 'd_601',
 'd_602',
 'd_603',
 'd_604',
 'd_605',
 'd_606',
 'd_607',
 'd_608',
 'd_609',
 'd_610',
 'd_611',
 'd_612',
 'd_613',
 'd_614',
 'd_615',
 'd_616',
 'd_617',
 'd_618',
 'd_619',
 'd_620',
 'd_621',
 'd_622',
 'd_623',
 'd_624',
 'd_625',
 'd_626',
 'd_627',
 'd_628',
 'd_629',
 'd_630',
 'd_631',
 'd_632',
 'd_633',
 'd_634',
 'd_635',
 'd_636',
 'd_637',
 'd_638',
 'd_639',
 'd_640',
 'd_641',
 'd_642',
 'd_643',
 'd_644',
 'd_645',
 'd_646',
 'd_647',
 'd_648',
 'd_649',
 'd_650',
 'd_651',
 'd_652',
 'd_653',
 'd_654',
 'd_655',
 'd_656',
 'd_657',
 'd_658',
 'd_659',
 'd_660',
 'd_661',
 'd_662',
 'd_663',
 'd_664',
 'd_665',
 'd_666',
 'd_667',
 'd_668',
 'd_669',
 'd_670',
 'd_671',
 'd_672',
 'd_673',
 'd_674',
 'd_675',
 'd_676',
 'd_677',
 'd_678',
 'd_679',
 'd_680',
 'd_681',
 'd_682',
 'd_683',
 'd_684',
 'd_685',
 'd_686',
 'd_687',
 'd_688',
 'd_689',
 'd_690',
 'd_691',
 'd_692',
 'd_693',
 'd_694',
 'd_695',
 'd_696',
 'd_697',
 'd_698',
 'd_699',
 'd_700',
 'd_701',
 'd_702',
 'd_703',
 'd_704',
 'd_705',
 'd_706',
 'd_707',
 'd_708',
 'd_709',
 'd_710',
 'd_711',
 'd_712',
 'd_713',
 'd_714',
 'd_715',
 'd_716',
 'd_717',
 'd_718',
 'd_719',
 'd_720',
 'd_721',
 'd_722',
 'd_723',
 'd_724',
 'd_725',
 'd_726',
 'd_727',
 'd_728',
 'd_729',
 'd_730',
 'd_731',
 'd_732',
 'd_733',
 'd_734',
 'd_735',
 'd_736',
 'd_737',
 'd_738',
 'd_739',
 'd_740',
 'd_741',
 'd_742',
 'd_743',
 'd_744',
 'd_745',
 'd_746',
 'd_747',
 'd_748',
 'd_749',
 'd_750',
 'd_751',
 'd_752',
 'd_753',
 'd_754',
 'd_755',
 'd_756',
 'd_757',
 'd_758',
 'd_759',
 'd_760',
 'd_761',
 'd_762',
 'd_763',
 'd_764',
 'd_765',
 'd_766',
 'd_767',
 'd_768',
 'd_769',
 'd_770',
 'd_771',
 'd_772',
 'd_773',
 'd_774',
 'd_775',
 'd_776',
 'd_777',
 'd_778',
 'd_779',
 'd_780',
 'd_781',
 'd_782',
 'd_783',
 'd_784',
 'd_785',
 'd_786',
 'd_787',
 'd_788',
 'd_789',
 'd_790',
 'd_791',
 'd_792',
 'd_793',
 'd_794',
 'd_795',
 'd_796',
 'd_797',
 'd_798',
 'd_799',
 'd_800',
 'd_801',
 'd_802',
 'd_803',
 'd_804',
 'd_805',
 'd_806',
 'd_807',
 'd_808',
 'd_809',
 'd_810',
 'd_811',
 'd_812',
 'd_813',
 'd_814',
 'd_815',
 'd_816',
 'd_817',
 'd_818',
 'd_819',
 'd_820',
 'd_821',
 'd_822',
 'd_823',
 'd_824',
 'd_825',
 'd_826',
 'd_827',
 'd_828',
 'd_829',
 'd_830',
 'd_831',
 'd_832',
 'd_833',
 'd_834',
 'd_835',
 'd_836',
 'd_837',
 'd_838',
 'd_839',
 'd_840',
 'd_841',
 'd_842',
 'd_843',
 'd_844',
 'd_845',
 'd_846',
 'd_847',
 'd_848',
 'd_849',
 'd_850',
 'd_851',
 'd_852',
 'd_853',
 'd_854',
 'd_855',
 'd_856',
 'd_857',
 'd_858',
 'd_859',
 'd_860',
 'd_861',
 'd_862',
 'd_863',
 'd_864',
 'd_865',
 'd_866',
 'd_867',
 'd_868',
 'd_869',
 'd_870',
 'd_871',
 'd_872',
 'd_873',
 'd_874',
 'd_875',
 'd_876',
 'd_877',
 'd_878',
 'd_879',
 'd_880',
 'd_881',
 'd_882',
 'd_883',
 'd_884',
 'd_885',
 'd_886',
 'd_887',
 'd_888',
 'd_889',
 'd_890',
 'd_891',
 'd_892',
 'd_893',
 'd_894',
 'd_895',
 'd_896',
 'd_897',
 'd_898',
 'd_899',
 'd_900',
 'd_901',
 'd_902',
 'd_903',
 'd_904',
 'd_905',
 'd_906',
 'd_907',
 'd_908',
 'd_909',
 'd_910',
 'd_911',
 'd_912',
 'd_913',
 'd_914',
 'd_915',
 'd_916',
 'd_917',
 'd_918',
 'd_919',
 'd_920',
 'd_921',
 'd_922',
 'd_923',
 'd_924',
 'd_925',
 'd_926',
 'd_927',
 'd_928',
 'd_929',
 'd_930',
 'd_931',
 'd_932',
 'd_933',
 'd_934',
 'd_935',
 'd_936',
 'd_937',
 'd_938',
 'd_939',
 'd_940',
 'd_941',
 'd_942',
 'd_943',
 'd_944',
 'd_945',
 'd_946',
 'd_947',
 'd_948',
 'd_949',
 'd_950',
 'd_951',
 'd_952',
 'd_953',
 'd_954',
 'd_955',
 'd_956',
 'd_957',
 'd_958',
 'd_959',
 'd_960',
 'd_961',
 'd_962',
 'd_963',
 'd_964',
 'd_965',
 'd_966',
 'd_967',
 'd_968',
 'd_969',
 'd_970',
 'd_971',
 'd_972',
 'd_973',
 'd_974',
 'd_975',
 'd_976',
 'd_977',
 'd_978',
 'd_979',
 'd_980',
 'd_981',
 'd_982',
 'd_983',
 'd_984',
 'd_985',
 'd_986',
 'd_987',
 'd_988',
 'd_989',
 'd_990',
 'd_991',
 'd_992',
 'd_993',
 'd_994',
 'd_995',
 'd_996',
 'd_997',
 'd_998',
 'd_999',
 'd_1000',
 ...]

In [21]:
fix = evaluation[d_cols].stack().reset_index(level=1)
fix.columns = ['d','unit_sale']
fix

            d  unit_sale
0         d_1          0
0         d_2          0
0         d_3          0
0         d_4          0
0         d_5          0
...       ...        ...
30489  d_1937          0
30489  d_1938          2
30489  d_1939          2
30489  d_1940          5
30489  d_1941          1

[59181090 rows x 2 columns]

In [22]:
my_data = evaluation.drop(d_cols, axis=1).join(fix)
my_data

,id,item_id,dept_id,cat_id,store_id,state_id,d,unit_sale
0,HOBBIES_1_001_CA_1_evaluation,HOBBIES_1_001,HOBBIES_1,HOBBIES,CA_1,CA,d_1,0
0,HOBBIES_1_001_CA_1_evaluation,HOBBIES_1_001,HOBBIES_1,HOBBIES,CA_1,CA,d_2,0
0,HOBBIES_1_001_CA_1_evaluation,HOBBIES_1_001,HOBBIES_1,HOBBIES,CA_1,CA,d_3,0
0,HOBBIES_1_001_CA_1_evaluation,HOBBIES_1_001,HOBBIES_1,HOBBIES,CA_1,CA,d_4,0
0,HOBBIES_1_001_CA_1_evaluation,HOBBIES_1_001,HOBBIES_1,HOBBIES,CA_1,CA,d_5,0
...,...,...,...,...,...,...,...,...
30489,FOODS_3_827_WI_3_evaluation,FOODS_3_827,FOODS_3,FOODS,WI_3,WI,d_1937,0
30489,FOODS_3_827_WI_3_evaluation,FOODS_3_827,FOODS_3,FOODS,WI_3,WI,d_1938,2
30489,FOODS_3_827_WI_3_evaluation,FOODS_3_827,FOODS_3,FOODS,WI_3,WI,d_1939,2
30489,FOODS_3_827_WI_3_evaluation,FOODS_3_827,FOODS_3,FOODS,WI_3,WI,d_1940,5
30489,FOODS_3_827_WI_3_evaluation,FOODS_3_827,FOODS_3,FOODS,WI_3,WI,d_1941,1

In [23]:
my_data['id']=my_data['id'].astype('category')
my_data['item_id']=my_data['item_id'].astype('category')
my_data['dept_id']=my_data['dept_id'].astype('category')
my_data['cat_id']=my_data['cat_id'].astype('category')
my_data['store_id']=my_data['store_id'].astype('category')
my_data['state_id']=my_data['state_id'].astype('category')
my_data['d']=my_data['d'].astype('category')

my_data['unit_sale']=pd.to_numeric(my_data['unit_sale'],downcast='unsigned')
my_data.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 59181090 entries, 0 to 30489
Data columns (total 8 columns):
 #   Column     Dtype
---  ------     -----
 0   id         category
 1   item_id    category
 2   dept_id    category
 3   cat_id     category
 4   store_id   category
 5   state_id   category
 6   d          category
 7   unit_sale  uint16
dtypes: category(7), uint16(1)
memory usage: 1.1 GB

In [24]:
calendar['date']=calendar['date'].astype('datetime64')

calendar['weekday']=calendar['weekday'].astype('category')
calendar['d']=calendar['d'].astype('category')
calendar['event_name_1']=calendar['event_name_1'].astype('category')
calendar['event_name_2']=calendar['event_name_2'].astype('category')
calendar['event_type_1']=calendar['event_type_1'].astype('category')
calendar['event_type_2']=calendar['event_type_2'].astype('category')
calendar['snap_CA']=calendar['snap_CA'].astype('bool')
calendar['snap_TX']=calendar['snap_TX'].astype('bool')
calendar['snap_WI']=calendar['snap_WI'].astype('bool')

calendar['wm_yr_wk'] = pd.to_numeric(calendar['wm_yr_wk'], downcast='unsigned')
calendar['wday'] = pd.to_numeric(calendar['wday'], downcast='unsigned')
calendar['month'] = pd.to_numeric(calendar['month'], downcast='unsigned')
calendar['year'] = pd.to_numeric(calendar['year'], downcast='unsigned')

calendar.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1969 entries, 0 to 1968
Data columns (total 14 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   date          1969 non-null   datetime64[ns]
 1   wm_yr_wk      1969 non-null   uint16
 2   weekday       1969 non-null   category
 3   wday          1969 non-null   uint8
 4   month         1969 non-null   uint8
 5   year          1969 non-null   uint16
 6   d             1969 non-null   category
 7   event_name_1  162 non-null    category
 8   event_type_1  162 non-null    category
 9   event_name_2  5 non-null      category
 10  event_type_2  5 non-null      category
 11  snap_CA       1969 non-null   bool
 12  snap_TX       1969 non-null   bool
 13  snap_WI       1969 non-null   bool
dtypes: bool(3), category(6), datetime64[ns](1), uint16(2), uint8(2)
memory usage: 128.3 KB

In [25]:
prices['store_id'] = prices['store_id'].astype('category')
prices['item_id'] = prices['item_id'].astype('category')

prices['wm_yr_wk'] = pd.to_numeric(prices['wm_yr_wk'], downcast='unsigned')
prices['sell_price'] = pd.to_numeric(prices['sell_price'], downcast='float')

prices.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6841121 entries, 0 to 6841120
Data columns (total 4 columns):
 #   Column      Dtype
---  ------      -----
 0   store_id    category
 1   item_id     category
 2   wm_yr_wk    uint16
 3   sell_price  float32
dtypes: category(2), float32(1), uint16(1)
memory usage: 58.8 MB

In [ ]:
my_data = my_data.merge(calendar, on='d', how='left').merge(prices, on=['store_id','item_id','wm_yr_wk'], how='left')

In [11]:
# my_data

In [ ]:
hobbies_1=my_data[my_data['dept_id']=="HOBBIES_1"]
hobbies_1 = hobbies_1.drop(hobbies_1[hobbies_1['unit_sale'] == 0].index)
hobbies_1.head()

In [ ]:
h1_df = pd.DataFrame(columns=['item_id', 'dept_id', 'cat_id', 'state_id', 'price',  'sale_perday', 'price_change', 'sale_change', 'elasticity'])

# Filter the DataFrame once
filtered_df = hobbies_1.groupby(['item_id', 'dept_id', 'cat_id', 'state_id']).filter(lambda x: len(x) > 0)

for (item_id, dept_id, cat_id, state_id), group_df in filtered_df.groupby(['item_id', 'dept_id', 'cat_id', 'state_id']):
    for sell_price in group_df['sell_price'].unique():
        item_df = group_df[group_df['sell_price'] == sell_price]
        sale_perday = item_df['unit_sale'].mean()

        hobbies_1_df = pd.DataFrame({'item_id': [item_id], 'dept_id': [dept_id], 'cat_id': [cat_id], 'state_id': [state_id], 'price': [sell_price],'sale_perday': [sale_perday]})
        hobbies_1_df = hobbies_1_df.dropna()

        h1_df = h1_df.append(hobbies_1_df, ignore_index=True)

h1_df['price_change'] = h1_df.groupby(['item_id', 'dept_id', 'cat_id', 'state_id'])['price'].pct_change() 
h1_df['sale_change'] = h1_df.groupby(['item_id', 'dept_id', 'cat_id', 'state_id'])['sale_perday'].pct_change() 
h1_df['elasticity'] = -h1_df['sale_change'] / h1_df['price_change']

h1_df = h1_df.dropna()

In [ ]:
h1_df['elasticity'] = h1_df['elasticity'].apply(lambda x: 0 if x < 0 else x)
h1_df

In [ ]:
h1_df["target_days"] = 7

grouped = h1_df.groupby(['item_id', 'state_id'])
h1_df['cost_price'] = grouped['price'].transform(lambda x: 0.5 * x.min())

discounts = [0, 10, 30,50]
new_rows = []
for index, row in h1_df.iterrows():
    for discount in discounts:
        new_row = row.copy()
        new_row['discount%'] = discount
        new_rows.append(new_row)

h1_opti = pd.DataFrame(new_rows)
h1_opti = h1_opti[["item_id","state_id","price","sale_perday","elasticity","target_days","discount%","cost_price"]]

h1_opti["stock on hand"] = 100

h1_opti["discount_price"] = (1-h1_opti["discount%"]/100)*h1_opti["price"]

h1_opti["predict_total_sale"] = (h1_opti["target_days"]*h1_opti["sale_perday"])*(1+abs((h1_opti["discount_price"]-h1_opti["price"])/h1_opti["price"])*h1_opti["elasticity"])
h1_opti.reset_index(drop=True, inplace=True)
h1_opti.loc[h1_opti["predict_total_sale"] > h1_opti["stock on hand"], "predict_total_sale"] = h1_opti["stock on hand"]

h1_opti

In [ ]:
h1_opti["cost"] = round(h1_opti['cost_price']*h1_opti["predict_total_sale"],2)

h1_opti["revenue"] = round(h1_opti["discount_price"]*h1_opti["predict_total_sale"],2)

h1_opti["profit"] = h1_opti["revenue"]-h1_opti["cost"]

h1_opti

In [58]:
h1_opti_copy = h1_opti

In [62]:
h1_opti_copy[h1_opti_copy['item_id']=="HOBBIES_1_100"]

,item_id,state_id,price,sale_perday,elasticity,target_days,discount%,cost_price,stock on hand,discount_price,predict_total_sale,cost,revenue,profit
2588,HOBBIES_1_100,CA,11.48,1.440783,1.645873,7,0,5.49,100,11.480,10.085479,55.37,115.78,60.41
2589,HOBBIES_1_100,CA,11.48,1.440783,1.645873,7,10,5.49,100,10.332,11.745420,64.48,121.35,56.87
2590,HOBBIES_1_100,CA,11.48,1.440783,1.645873,7,30,5.49,100,8.036,15.065303,82.71,121.06,38.35
2591,HOBBIES_1_100,CA,11.48,1.440783,1.645873,7,50,5.49,100,5.740,18.385186,100.93,105.53,4.60
2592,HOBBIES_1_100,CA,10.98,1.388110,0.000000,7,0,5.49,100,10.980,9.716767,53.35,106.69,53.34
2593,HOBBIES_1_100,CA,10.98,1.388110,0.000000,7,10,5.49,100,9.882,9.716767,53.35,96.02,42.67
2594,HOBBIES_1_100,CA,10.98,1.388110,0.000000,7,30,5.49,100,7.686,9.716767,53.35,74.68,21.33
2595,HOBBIES_1_100,CA,10.98,1.388110,0.000000,7,50,5.49,100,5.490,9.716767,53.35,53.35,0.00
2596,HOBBIES_1_100,CA,11.28,1.348333,1.048771,7,0,5.49,100,11.280,9.438333,51.82,106.46,54.64
2597,HOBBIES_1_100,CA,11.28,1.348333,1.048771,7,10,5.49,100,10.152,10.428198,57.25,105.87,48.62
2598,HOBBIES_1_100,CA,11.28,1.348333,1.048771,7,30,5.49,100,7.896,12.407928,68.12,97.97,29.85
2599,HOBBIES_1_100,CA,11.28,1.348333,1.048771,7,50,5.49,100,5.640,14.387657,78.99,81.15,2.16
2600,HOBBIES_1_100,TX,11.48,1.251969,0.039120,7,0,5.24,100,11.480,8.763780,45.92,100.61,54.69
2601,HOBBIES_1_100,TX,11.48,1.251969,0.039120,7,10,5.24,100,10.332,8.798063,46.10,90.90,44.80
2602,HOBBIES_1_100,TX,11.48,1.251969,0.039120,7,30,5.24,100,8.036,8.866631,46.46,71.25,24.79
2603,HOBBIES_1_100,TX,11.48,1.251969,0.039120,7,50,5.24,100,5.740,8.935198,46.82,51.29,4.47
2604,HOBBIES_1_100,TX,10.98,1.180531,0.000000,7,0,5.24,100,10.980,8.263717,43.30,90.74,47.44
2605,HOBBIES_1_100,TX,10.98,1.180531,0.000000,7,10,5.24,100,9.882,8.263717,43.30,81.66,38.36
2606,HOBBIES_1_100,TX,10.98,1.180531,0.000000,7,30,5.24,100,7.686,8.263717,43.30,63.51,20.21
2607,HOBBIES_1_100,TX,10.98,1.180531,0.000000,7,50,5.24,100,5.490,8.263717,43.30,45.37,2.07
2608,HOBBIES_1_100,TX,11.28,1.137681,1.328472,7,0,5.24,100,11.280,7.963768,41.73,89.83,48.10
2609,HOBBIES_1_100,TX,11.28,1.137681,1.328472,7,10,5.24,100,10.152,9.021732,47.27,91.59,44.32
2610,HOBBIES_1_100,TX,11.28,1.137681,1.328472,7,30,5.24,100,7.896,11.137661,58.36,87.94,29.58
2611,HOBBIES_1_100,TX,11.28,1.137681,1.328472,7,50,5.24,100,5.640,13.253589,69.45,74.75,5.30
2612,HOBBIES_1_100,TX,10.48,1.333333,2.424840,7,0,5.24,100,10.480,9.333333,48.91,97.81,48.90
2613,HOBBIES_1_100,TX,10.48,1.333333,2.424840,7,10,5.24,100,9.432,11.596517,60.77,109.38,48.61
2614,HOBBIES_1_100,TX,10.48,1.333333,2.424840,7,30,5.24,100,7.336,16.122886,84.48,118.28,33.80
2615,HOBBIES_1_100,TX,10.48,1.333333,2.424840,7,50,5.24,100,5.240,20.649254,108.20,108.20,0.00
2616,HOBBIES_1_100,TX,11.98,1.470588,0.000000,7,0,5.24,100,11.980,10.294118,53.94,123.32,69.38
2617,HOBBIES_1_100,TX,11.98,1.470588,0.000000,7,10,5.24,100,10.782,10.294118,53.94,110.99,57.05
2618,HOBBIES_1_100,TX,11.98,1.470588,0.000000,7,30,5.24,100,8.386,10.294118,53.94,86.33,32.39
2619,HOBBIES_1_100,TX,11.98,1.470588,0.000000,7,50,5.24,100,5.990,10.294118,53.94,61.66,7.72
2620,HOBBIES_1_100,WI,11.48,1.204444,0.696441,7,0,5.49,100,11.480,8.431111,46.29,96.79,50.50
2621,HOBBIES_1_100,WI,11.48,1.204444,0.696441,7,10,5.49,100,10.332,9.018289,49.51,93.18,43.67
2622,HOBBIES_1_100,WI,11.48,1.204444,0.696441,7,30,5.49,100,8.036,10.192643,55.96,81.91,25.95
2623,HOBBIES_1_100,WI,11.48,1.204444,0.696441,7,50,5.49,100,5.740,11.366998,62.40,65.25,2.85
2624,HOBBIES_1_100,WI,10.98,1.161889,0.000000,7,0,5.49,100,10.980,8.133221,44.65,89.30,44.65
2625,HOBBIES_1_100,WI,10.98,1.161889,0.000000,7,10,5.49,100,9.882,8.133221,44.65,80.37,35.72
2626,HOBBIES_1_100,WI,10.98,1.161889,0.000000,7,30,5.49,100,7.686,8.133221,44.65,62.51,17.86
2627,HOBBIES_1_100,WI,10.98,1.161889,0.000000,7,50,5.49,100,5.490,8.133221,44.65,44.65,0.00
2628,HOBBIES_1_100,WI,11.28,1.131274,0.964372,7,0,5.49,100,11.280,7.918919,43.47,89.33,45.86
2629,HOBBIES_1_100,WI,11.28,1.131274,0.964372,7,10,5.49,100,10.152,8.682597,47.67,88.15,40.48
2630,HOBBIES_1_100,WI,11.28,1.131274,0.964372,7,30,5.49,100,7.896,10.209953,56.05,80.62,24.57
2631,HOBBIES_1_100,WI,11.28,1.131274,0.964372,7,50,5.49,100,5.640,11.737309,64.44,66.20,1.76
2632,HOBBIES_1_100,WI,12.00,1.000000,1.817974,7,0,5.49,100,12.000,7.000000,38.43,84.00,45.57
2633,HOBBIES_1_100,WI,12.00,1.000000,1.817974,7,10,5.49,100,10.800,8.272582,45.42,89.34,43.92
2634,HOBBIES_1_100,WI,12.00,1.000000,1.817974,7,30,5.49,100,8.400,10.817746,59.39,90.87,31.48
2635,HOBBIES_1_100,WI,12.00,1.000000,1.817974,7,50,5.49,100,6.000,13.362910,73.36,80.18,6.82
2636,HOBBIES_1_100,WI,11.98,1.136364,81.816309,7,0,5.49,100,11.980,7.954545,43.67,95.30,51.63
2637,HOBBIES_1_100,WI,11.98,1.136364,81.816309,7,10,5.49,100,10.782,73.035700,400.97,787.47,386.50
2638,HOBBIES_1_100,WI,11.98,1.136364,81.816309,7,30,5.49,100,8.386,100.000000,549.00,838.60,289.60
2639,HOBBIES_1_100,WI,11.98,1.136364,81.816309,7,50,5.49,100,5.990,100.000000,549.00,599.00,50.00

In [16]:
h1_opti = h1_opti.loc[h1_opti.groupby(['item_id', 'state_id','price'])['profit'].idxmax()]
h1_opti.reset_index(drop=True, inplace=True)
h1_opti

,item_id,state_id,price,sale_perday,elasticity,target_days,discount%,cost_price,stock on hand,discount_price,predict_total_sale,cost,revenue,profit
0,HOBBIES_1_001,CA,8.38,1.721649,0.000000,7,0,4.130,100,8.380,12.051546,49.77,100.99,51.22
1,HOBBIES_1_001,TX,8.26,1.278431,0.000000,7,0,2.500,100,8.260,8.949020,22.37,73.92,51.55
2,HOBBIES_1_001,WI,8.62,1.000000,7.698170,7,10,4.130,100,7.758,12.388719,51.17,96.11,44.94
3,HOBBIES_1_002,CA,2.00,1.000000,0.000000,7,0,1.000,100,2.000,7.000000,7.00,14.00,7.00
4,HOBBIES_1_002,TX,2.97,1.000000,0.000000,7,0,1.485,100,2.970,7.000000,10.40,20.79,10.39
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
974,HOBBIES_1_423,TX,7.78,1.528947,0.000000,7,0,3.810,100,7.780,10.702632,40.78,83.27,42.49
975,HOBBIES_1_423,WI,7.98,1.000000,10.579778,7,30,3.890,100,5.586,29.217534,113.66,163.21,49.55
976,HOBBIES_1_424,CA,1.77,2.224558,2.371262,7,10,0.680,100,1.593,19.264415,13.10,30.69,17.59
977,HOBBIES_1_424,TX,1.27,6.000000,9.262408,7,10,0.500,100,1.143,80.902113,40.45,92.47,52.02
978,HOBBIES_1_424,WI,1.30,5.000000,9.568625,7,10,0.650,100,1.170,68.490189,44.52,80.13,35.61

In [64]:
h1_opti[h1_opti['item_id']=="HOBBIES_1_100"]

,item_id,state_id,price,sale_perday,elasticity,target_days,discount%,cost_price,stock on hand,discount_price,predict_total_sale,cost,revenue,profit
234,HOBBIES_1_100,CA,11.48,1.440783,1.645873,7,0,5.49,100,11.480,10.085479,55.37,115.78,60.41
235,HOBBIES_1_100,TX,11.98,1.470588,0.000000,7,0,5.24,100,11.980,10.294118,53.94,123.32,69.38
236,HOBBIES_1_100,WI,11.98,1.136364,81.816309,7,10,5.49,100,10.782,73.035700,400.97,787.47,386.50

In [ ]:
h1_opti.to_csv('h1_opti.csv')
h2_opti.to_csv('h2_opti.csv')
ho1_opti.to_csv('ho1_opti.csv')
ho2_opti.to_csv('ho2_opti.csv')
f1_opti.to_csv('f1_opti.csv')
f2_opti.to_csv('f2_opti.csv')
f3_opti.to_csv('f3_opti.csv')